points/urls.py
from django.urls import path

from points.views import PointCreateView, PointEditView, PointDetailView

urlpatterns = [
    path('detail/<int:pk>', PointDetailView.as_view(), name='detail'),
    path("create", PointCreateView.as_view(), name="create"),
    path("edit/<int:pk>", PointEditView.as_view(), name="edit"),
]

sapphire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path("", lambda request: redirect("sites:list")),
    path("sites/", include(("sites.urls", "sites"),
                           namespace="sites")),
    path("points/", include(("points.urls", "points"),
                            namespace="points")),
]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT)

handler404 = 'sapphire.views.custom_not_found_view'
handler500 = 'sapphire.views.custom_error_view'

sites/urls.py
from django.urls import path
from sites.views import SiteListView, SiteSearchListView, SiteDetailView

urlpatterns = [
    path("", SiteListView.as_view(), name="list"),
    path("search", SiteSearchListView.as_view(), name="search"),
    path("<int:pk>", SiteDetailView.as_view(), name="detail"),
]

points/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.urls import reverse


class PointCategory(models.Model):
    name = models.CharField('site name', max_length=100)

    class Meta:
        indexes = [
            models.Index(fields=['name'], name='name_idx'),
        ]

    def __str__(self):
        return self.name


class WithCategoryManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.select_related('category')


class Point(models.Model):
    """
    it could be category 'hazard' or any other, that's why it is not called Hazard and has FK to PointCategory
    """
    title = models.CharField('point title', max_length=100)
    description = models.CharField('point description', max_length=256)
    geom = models.PointField(srid=settings.DEFAULT_SRID)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(PointCategory, related_name='points', on_delete=models.CASCADE)
    objects = WithCategoryManager()

    class Meta:
        indexes = [
            models.Index(fields=['title'], name='points_title_idx'),
        ]

    def __str__(self):
        return f'{self.category.name} point: {self.title} with pk <{self.pk}>'

    @property
    def popup_info(self):
        """
        Formatted text for use on the map
        :return:
        """
        return f'<p>category: {self.category}</p>' \
               f'<p>title: {self.title}</p>' \
               f'<p>description: {self.description}</p>' \
               f'<p><a href={self.get_absolute_url()}>view</a></p>'

    @property
    def category_name(self):
        """
        Get category name
        :return:
        """
        return self.category.name

    @property
    def found_in_sites(self):
        """
        list of sites that contains the point
        :return:
        """
        from sites.models import Site  # deal with cross import
        return Site.objects.filter(polygon__intersects=self.geom)

    def get_absolute_url(self):
        return reverse('points:detail', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse('points:edit', kwargs={'pk': self.pk})

sites/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.urls import reverse

from points.models import Point


class Site(models.Model):
    title = models.CharField('title', max_length=100)
    polygon = models.PolygonField('polygon', srid=settings.DEFAULT_SRID)

    class Meta:
        indexes = [
            models.Index(fields=['title'], name='sites_title_idx'),
        ]

    def __str__(self):
        return f'Site: {self.title} with pk <{self.pk}>'

    @property
    def all_points_within(self):
        """
        Get all points within site
        :return:
        """
        return Point.objects.filter(geom__within=self.polygon)

    def get_absolute_url(self):
        return reverse('sites:detail', kwargs={'pk': self.pk})

points/forms.py
from django.contrib.gis import forms
from django.conf import settings
from points.models import Point


class PointForm(forms.ModelForm):
    class Meta:
        model = Point
        fields = ('title', 'description', 'category', 'geom',)
        widgets = {
            'geom': forms.OSMWidget(
                attrs={
                    'map_width': 'auto',
                    'map_height': 500,
                    'default_zoom': settings.OSM_WIDGET_DEFAULT_ZOOM,
                    'default_lon': settings.OSM_WIDGET_DEFAULT_LON,
                    'default_lat': settings.OSM_WIDGET_DEFAULT_LAT
                }
            )
        }

points/views.py
from django.urls import reverse_lazy

from points.forms import PointForm
from django.views import generic

from points.models import Point


class PointCreateView(generic.CreateView):
    template_name = 'points/create_or_edit.html'
    form_class = PointForm
    model = Point

    def get_success_url(self):
        return reverse_lazy('points:detail', kwargs={'pk': self.object.pk})


class PointEditView(generic.UpdateView):
    template_name = 'points/create_or_edit.html'
    form_class = PointForm
    model = Point

    def get_success_url(self):
        return reverse_lazy('points:detail', kwargs={'pk': self.object.pk})


class PointDetailView(generic.DetailView):
    model = Point
    template_name = 'points/detail.html'

sapphire/views.py
from django.shortcuts import render


def custom_not_found_view(request, *args, **kwargs):
    return render(request, '404.html', status=404)


def custom_error_view(request, *args, **kwargs):
    return render(request, '500.html', status=500)

sites/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from sites.models import Site


class SiteListView(generic.ListView):
    paginate_by = 10
    template_name = 'sites/list.html'
    context_object_name = 'all_sites'

    def get_queryset(self):
        return Site.objects.order_by('pk')


class SiteSearchListView(generic.ListView):
    paginate_by = 10
    template_name = 'sites/list.html'
    context_object_name = 'search_results'
    search_field = 'title_q'

    def get_queryset(self):
        title_q = self.request.GET.get(self.search_field)
        if not title_q:
            raise Http404('Empty search request provided')

        found_entities = Site.objects.filter(title__icontains=title_q)
        return found_entities


class SiteDetailView(generic.DetailView):
    model = Site
    template_name = 'sites/detail.html'

points/templates/points/create_or_edit.html
{% extends "base.html" %}
{% block head %}
    {{ form.media }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row my-12">
            <div class="col-md-12">
                {% if form %}
                    {% if form.errors %}
                        <ul class="errors">
                            {% for error in form.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="row">
                                <div class="col-12">
                                    <label class="form-label fw-bold">{{ field.label }}</label></div>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="col-md-12 bg-light clearfix">
                            <button class="btn btn-success float-end" type="submit">Submit</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

points/templates/points/detail.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
    <div class="row">
        <div class="col-12 text-center m-2">
            {{ object }}
        </div>
        <div class="col-12 text-left m-2">
            <div>Title: {{ object.title }}</div>
            <div>Category: {{ object.category }}</div>
            <div>Description: {{ object.description }}</div>
            <div>Created at: {{ object.created_at|naturaltime }}</div>
            <div>Updated at: {{ object.updated_at }}</div>
            <div><a class="btn btn-primary" href="{{ object.get_edit_url }}" role="button">Edit point</a></div>
        </div>
        <div>
            {% if object.found_in_sites %}
                <div class="col-12 text-left m-2">
                    <div>List of sites that contains this point:</div>
                </div>
                {% include "sites/sites_listing_block.html" with sites=object.found_in_sites %}
            {% else %}
                <div>This point does not occur in any of the sites polygons.</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

sites/templates/sites/detail.html
{% extends "base.html" %}
{% load geojson_tags %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-12 text-center m-2">
            {{ object }}
        </div>
        <div class="col-12 text-center m-2">
            <a href="{% url 'points:create' %}">
                <button class="btn btn-secondary">Add point</button>
            </a>
        </div>
    </div>
    <div id="map"></div>
    <script>
        let map = L.map('map');
        let customIcon = L.Icon.extend({
            options: {
                shadowUrl: '{% static "misc/marker-shadow.png" %}',
                iconSize: [25, 41],
                iconAnchor: [12, 41],
                popupAnchor: [1, -34],
                shadowSize: [41, 41]
            }
        });
        let shelterIcon = new customIcon({iconUrl: '{% static "misc/marker-icon-2x-green.png" %}'});
        let hazardIcon = new customIcon({iconUrl: '{% static "misc/marker-icon-2x-red.png" %}'});

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);
        let polygon = L.geoJSON({{ object.polygon|geojsonfeature|safe}}).addTo(map);
        let allPoints = {{ object.all_points_within|geojsonfeature:"popup_info,category_name"|safe }};
        function onEachFeature(feature, layer) {
            if (feature.properties && feature.properties.popup_info) {
                layer.bindPopup(feature.properties.popup_info).openPopup();
                if (feature.properties.category_name === 'Hazard') {
                      layer.setIcon(hazardIcon);
                      layer.addTo(map);
                }
                else if (feature.properties.category_name === 'Shelter') {
                    layer.setIcon(shelterIcon);
                    layer.addTo(map);
                }
            }
        }
        L.geoJson(allPoints, {onEachFeature: onEachFeature}).addTo(map);
        map.fitBounds(polygon.getBounds());
    </script>
{% endblock %}

sites/templates/sites/list.html
{% extends "base.html" %}
{% block content %}
    {% if current_search_value %}
        <div class="row">
            <div class="col-12 text-left m-2">
                Your current search: {{ request.GET.title_q }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12 text-left m-2">
            Available sites:
        </div>
    </div>
    {% if page_obj %}
        {% include "sites/sites_listing_block.html" with sites=page_obj %}
        <nav aria-label="page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}{{ current_search_value }}">Previous</a>
                    </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link" href="#">Page {{ page_obj.number }}
                    of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ current_search_value }}">Next</a>
                    </li>
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.paginator.num_pages }}{{ current_search_value }}">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <div class="row">
            <div class="col-12 text-left">
                There's no such thing as nothing. In every nothing, there's a something. In fact, there could be
                everything!
            </div>
        </div>
    {% endif %}
{% endblock %}

sites/templates/sites/sites_listing_block.html
{% if sites %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">TITLE</th>
            <th scope="col">POINTS WITHIN</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% for site in sites %}
            <tr>
                <th scope="row">{{ site.id }}</th>
                <td>{{ site.title }}</td>
                <td>{{ site.all_points_within.count }}</td>
                <td><a href="{{ site.get_absolute_url }}"><button class="btn btn-outline-info" type="button">view</button></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static "misc/sapphire.png" %}">
    <title>{{ project_name }} | Home assignment </title>
    <link href="{% static "misc/custom.css" %}" rel="stylesheet">

    <link href="{% static "bootstrap5/css/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "bootstrap5/js/bootstrap.bundle.min.js" %}"></script>

    <link rel="stylesheet" href="{% static "leaflet/leaflet.css" %}"/>
    <script src="{% static "leaflet/leaflet.js" %}"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light blue" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'sites:list' %}">
                <img src="{% static "misc/sapphire.png" %}" alt="" width="25" height="25"
                     class="d-inline-block align-text-top">
                Sapphire
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'sites:list' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'points:create' %}">Add point</a>
                    </li>
                </ul>
                <form class="d-flex" action="{% url 'sites:search' %}" method="get">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="title_q" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
</div>
</body>
</html>